### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by jeremiahtenbrink** [WebCrew/TodGmbH-HumHub-Theme#2]
I want to edit the Registration form after the user submits a email address and gets the link to the registration form, but when I edit the registration form in your theme/views/user/auth/createAccount.php file. It has no effect on the registration form. I'm just wondering where it is I would need to edit in order to edit the Registration Form.

**Comment by WebCrew** [comment]
as far as I remember You have to do also some edits in:
theme/views/user/auth/login.php    
start at around line 49
